import type { Metadata } from "next";
import { Open_Sans} from "next/font/google";
import "./globals.css";
import Footer from "./ui/footer";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
				<main className="flex-grow">
					{children}
				</main>
				<Footer />
			</body>
    </html>
  );
}
